### ISSUE TITLE
constant data not loading

### ISSUE THREAD

**Issue by tdupu** [tdupu/submission_tools#18]
Traceback (most recent call last):
  File "new_submission.py", line 30, in <module>
    PATH_TO_DATA = get_path_to_data()
  File "/users/t/d/tdupuy/dev/submission_tools/submission_functions.py", line 190, in get_path_to_data
    constant_data = get_constant_data(path_to_data)
  File "/users/t/d/tdupuy/dev/submission_tools/submission_functions.py", line 165, in get_constant_data
    constant_data = json.load(f)
UnboundLocalError: local variable 'f' referenced before assignment

**Comment by tdupu** [comment]
Fixed. Needs to be tested.
